# Generated by Django 3.2.16 on 2022-12-03 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import trooper.members.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Committee',
                'verbose_name_plural': 'Committees',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Patrol',
                'verbose_name_plural': 'Patrols',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PatrolMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='from')),
                ('end', models.DateField(blank=True, null=True, verbose_name='until')),
                ('member', models.ForeignKey(limit_choices_to=trooper.members.models.Member.youth_choices, on_delete=django.db.models.deletion.CASCADE, related_name='patrol_members', related_query_name='patrol_member', to=settings.AUTH_USER_MODEL)),
                ('patrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrol_members', related_query_name='patrol_member', to='assignments.patrol')),
            ],
            options={
                'verbose_name': 'Patrol Member',
                'verbose_name_plural': 'Patrol Members',
                'db_table': 'patrol_member',
                'ordering': ['-end', 'member'],
            },
        ),
        migrations.AddField(
            model_name='patrol',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='patrols', through='assignments.PatrolMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Scoutmaster'), (2, 'Assistant Scoutmaster')], verbose_name='leadership role')),
                ('start', models.DateField(verbose_name='from')),
                ('end', models.DateField(blank=True, null=True, verbose_name='until')),
                ('member', models.ForeignKey(limit_choices_to=trooper.members.models.Member.adult_choices, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leadership',
                'verbose_name_plural': 'Leadership',
                'ordering': ['-start', '-role', 'member'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='from')),
                ('end', models.DateField(blank=True, null=True, verbose_name='until')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_members', related_query_name='committee_member', to='assignments.committee')),
                ('member', models.ForeignKey(limit_choices_to=trooper.members.models.Member.adult_choices, on_delete=django.db.models.deletion.CASCADE, related_name='committee_members', related_query_name='committee_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Committee Member',
                'verbose_name_plural': 'Committee Members',
                'db_table': 'committee_member',
                'ordering': ['-end', 'member'],
            },
        ),
        migrations.AddField(
            model_name='committee',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='committees', through='assignments.CommitteeMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
