# Generated by Django 3.2.18 on 2023-04-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Committee',
                'verbose_name_plural': 'Committees',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='from')),
                ('end', models.DateField(blank=True, null=True, verbose_name='until')),
            ],
            options={
                'verbose_name': 'Committee Member',
                'verbose_name_plural': 'Committee Members',
                'db_table': 'assignments_committee_member',
                'ordering': ['-end', 'member'],
            },
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Scoutmaster'), (2, 'Assistant Scoutmaster')], verbose_name='leadership role')),
                ('start', models.DateField(verbose_name='from')),
                ('end', models.DateField(blank=True, null=True, verbose_name='until')),
            ],
            options={
                'verbose_name': 'Leader',
                'verbose_name_plural': 'Leaders',
                'ordering': ['-start', '-role', 'member'],
            },
        ),
        migrations.CreateModel(
            name='Patrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Patrol',
                'verbose_name_plural': 'Patrols',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PatrolMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='from')),
                ('end', models.DateField(blank=True, null=True, verbose_name='until')),
            ],
            options={
                'verbose_name': 'Patrol Member',
                'verbose_name_plural': 'Patrol Members',
                'db_table': 'assignments_patrol_member',
                'ordering': ['-end', 'member'],
            },
        ),
    ]
