# Generated by Django 3.2.17 on 2023-02-16 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='committeemember',
            table='assignments_committee_member',
        ),
    ]
