# Generated by Django 3.2.18 on 2023-03-28 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_auto_20230217_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leader',
            options={'ordering': ['-start', 'role', 'member'], 'verbose_name': 'Leader', 'verbose_name_plural': 'Leaders'},
        ),
    ]
