# Generated by Django 3.2.16 on 2022-10-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Allow other members to see this address in the Troop directory.', verbose_name='published in the directory'),
        ),
        migrations.AlterField(
            model_name='email',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Allow other members to see this address in the Troop directory.', verbose_name='published in directory'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Allow other members to see this number in the Troop directory.', verbose_name='published in directory'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['content_type', 'object_id'], name='address_boo_content_9fdbea_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['content_type', 'object_id'], name='address_boo_content_42c489_idx'),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['content_type', 'object_id'], name='address_boo_content_6d00c0_idx'),
        ),
    ]
