# Generated by Django 3.2.16 on 2022-10-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0002_auto_20221021_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='label',
            field=models.CharField(blank=True, choices=[('H', 'Home'), ('S', 'School'), ('W', 'Work'), ('B', 'P.O. Box'), ('O', 'Other')], max_length=1, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='email',
            name='label',
            field=models.CharField(blank=True, choices=[('H', 'Home'), ('S', 'School'), ('W', 'Work'), ('O', 'Other')], max_length=1, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='label',
            field=models.CharField(blank=True, choices=[('H', 'Home'), ('M', 'Mobile'), ('S', 'School'), ('W', 'Work'), ('O', 'Other')], max_length=1, verbose_name='label'),
        ),
    ]
