# Generated by Django 3.2.18 on 2023-03-01 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0003_auto_20230110_0533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='zipcode',
            new_name='zip_code',
        ),
    ]
