# Generated by Django 3.2.18 on 2023-03-03 00:34

from django.db import migrations, models


def forwards(apps, schema_editor):
    Phone = apps.get_model("address_book", "Phone")
    for phone in Phone.objects.all():
        if phone.label == "H":
            phone.label = "HOME"
        if phone.label == "M":
            phone.label = "CELL"
        if phone.label == "W":
            phone.label = "WORK"
        if phone.label == "S":
            phone.label = ""
        if phone.label == "O":
            phone.label = ""
        phone.save()


def reverse(apps, schema_editor):
    Phone = apps.get_model("address_book", "Phone")
    for phone in Phone.objects.all():
        if phone.label == "HOME":
            phone.label = "H"
        if phone.label == "CELL":
            phone.label = "M"
        if phone.label == "WORK":
            phone.label = "W"
        if phone.label == "FAX":
            phone.label = "O"
        phone.save()


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0004_rename_zipcode_address_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='label',
            field=models.CharField(blank=True, choices=[('HOME', 'Home'), ('CELL', 'Mobile'), ('FAX', 'Fax'), ('WORK', 'Work')], max_length=4, verbose_name='label'),
        ),
        migrations.RunPython(forwards, reverse),
    ]
