# Generated by Django 3.2.18 on 2023-03-03 01:04

from django.db import migrations, models


def forwards(apps, schema_editor):
    Address = apps.get_model("address_book", "Address")
    for address in Address.objects.all():
        if address.label == "H":
            address.label = "HOME"
        if address.label == "W":
            address.label = "WORK"
        if address.label == "S":
            address.label = "SCHOOL"
        if address.label == "O":
            address.label = ""
        address.save()


def reverse(apps, schema_editor):
    Address = apps.get_model("address_book", "Address")
    for address in Address.objects.all():
        if address.label == "HOME":
            address.label = "H"
        if address.label == "SCHOOL":
            address.label = "S"
        if address.label == "WORK":
            address.label = "W"
        address.save()


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0006_alter_email_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='label',
            field=models.CharField(blank=True, choices=[('HOME', 'Home'), ('WORK', 'Work'), ('SCHOOL', 'School'), ('POB', 'P.O. Box')], max_length=6, verbose_name='label'),
        ),
        migrations.RunPython(forwards, reverse),
    ]
