# Generated by Django 4.2 on 2023-04-12 18:46

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Trooper", max_length=20, verbose_name="display name"
                    ),
                ),
                (
                    "domain",
                    models.URLField(
                        help_text="The domain name associated with this website",
                        verbose_name="domain name",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="A brief description of this Troop",
                        max_length=255,
                        verbose_name="description",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="A recognizable icon to visually identify your Troop",
                        upload_to="img",
                        verbose_name="logo",
                    ),
                ),
                ("footer_text", models.TextField(blank=True, verbose_name="footer")),
                (
                    "primary",
                    colorfield.fields.ColorField(
                        default="#003f87",
                        image_field=None,
                        max_length=18,
                        samples=[
                            ("#ce1126", "Scouting Red"),
                            ("#003f87", "Scouting Blue"),
                            ("#d6cebd", "Scouting Tan"),
                            ("#515354", "Warm Gray"),
                            ("#243e2c", "Olive"),
                            ("#fdc116", "Gold"),
                            ("#ffffff", "White"),
                            ("#c54250", "Light Red"),
                            ("#860d1a", "Dark Red"),
                            ("#9ab3d5", "Pale Blue"),
                            ("#003366", "Dark Blue"),
                            ("#e9e9e4", "Light Tan"),
                            ("#ad9d7b", "Dark Tan"),
                            ("#858787", "Pale Gray"),
                            ("#232528", "Dark Gray"),
                        ],
                        verbose_name="Primary Color",
                    ),
                ),
                (
                    "secondary",
                    colorfield.fields.ColorField(
                        default="#515354",
                        image_field=None,
                        max_length=18,
                        samples=[
                            ("#ce1126", "Scouting Red"),
                            ("#003f87", "Scouting Blue"),
                            ("#d6cebd", "Scouting Tan"),
                            ("#515354", "Warm Gray"),
                            ("#243e2c", "Olive"),
                            ("#fdc116", "Gold"),
                            ("#ffffff", "White"),
                            ("#c54250", "Light Red"),
                            ("#860d1a", "Dark Red"),
                            ("#9ab3d5", "Pale Blue"),
                            ("#003366", "Dark Blue"),
                            ("#e9e9e4", "Light Tan"),
                            ("#ad9d7b", "Dark Tan"),
                            ("#858787", "Pale Gray"),
                            ("#232528", "Dark Gray"),
                        ],
                        verbose_name="Secondary Color",
                    ),
                ),
                (
                    "body_bg",
                    colorfield.fields.ColorField(
                        default="#d6cebd",
                        image_field=None,
                        max_length=18,
                        samples=[
                            ("#ce1126", "Scouting Red"),
                            ("#003f87", "Scouting Blue"),
                            ("#d6cebd", "Scouting Tan"),
                            ("#515354", "Warm Gray"),
                            ("#243e2c", "Olive"),
                            ("#fdc116", "Gold"),
                            ("#ffffff", "White"),
                            ("#c54250", "Light Red"),
                            ("#860d1a", "Dark Red"),
                            ("#9ab3d5", "Pale Blue"),
                            ("#003366", "Dark Blue"),
                            ("#e9e9e4", "Light Tan"),
                            ("#ad9d7b", "Dark Tan"),
                            ("#858787", "Pale Gray"),
                            ("#232528", "Dark Gray"),
                        ],
                        verbose_name="Body Background Color",
                    ),
                ),
                (
                    "navbar_bg",
                    colorfield.fields.ColorField(
                        default="#243e2c",
                        image_field=None,
                        max_length=18,
                        samples=[
                            ("#ce1126", "Scouting Red"),
                            ("#003f87", "Scouting Blue"),
                            ("#d6cebd", "Scouting Tan"),
                            ("#515354", "Warm Gray"),
                            ("#243e2c", "Olive"),
                            ("#fdc116", "Gold"),
                            ("#ffffff", "White"),
                            ("#c54250", "Light Red"),
                            ("#860d1a", "Dark Red"),
                            ("#9ab3d5", "Pale Blue"),
                            ("#003366", "Dark Blue"),
                            ("#e9e9e4", "Light Tan"),
                            ("#ad9d7b", "Dark Tan"),
                            ("#858787", "Pale Gray"),
                            ("#232528", "Dark Gray"),
                        ],
                        verbose_name="Navbar Background Color",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration",
                "verbose_name_plural": "Configuration",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.ImageField(upload_to="website", verbose_name="file")),
                (
                    "title",
                    models.CharField(blank=True, max_length=150, verbose_name="title"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of this page. Will be shown at the top of the page, in navigation, and in the browser's title bar.",
                        max_length=100,
                        verbose_name="title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="The part of the page's URL that comes after the slash. Useful in providing meaningful links.",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "is_builtin",
                    models.CharField(
                        blank=True,
                        choices=[
                            (None, "custom webpage"),
                            ("HOME", "Home Page"),
                            ("ABOUT", "About Us"),
                            ("CONTACT", "Contact Form"),
                            ("SIGNUP", "Sign Up Form"),
                        ],
                        help_text="Some pages, such as the home page, require special treatment. If this is to be one of those special pages, you can specify it here.",
                        max_length=7,
                        null=True,
                        unique=True,
                        verbose_name="page",
                    ),
                ),
                (
                    "in_navbar",
                    models.BooleanField(
                        default=True,
                        help_text="Determines whether this page should appear in the site's navigation bar.",
                        verbose_name="include in navigation",
                    ),
                ),
                (
                    "navbar_order",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Specify the order this page should appear on the site's navigation bar.",
                        null=True,
                        unique=True,
                        verbose_name="navigation order",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this page was first added to the database.",
                        verbose_name="created",
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this page was last saved to the database.",
                        verbose_name="modified",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
            },
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("ANONYMOUS", "Anonymous/Guests"),
                            ("PUBLIC", "Everyone"),
                            ("MEMBERS", "Members Only"),
                        ],
                        default="MEMBERS",
                        help_text="Controls who will be allowed to view this content.",
                        max_length=9,
                        verbose_name="visibility",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="heading"
                    ),
                ),
                (
                    "bookmark",
                    models.SlugField(
                        blank=True,
                        help_text="Can be used to link directly to this content block on a webpage.",
                        verbose_name="bookmark",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="The main body of this content block",
                        verbose_name="body",
                    ),
                ),
                (
                    "gallery_controls",
                    models.CharField(
                        blank=True,
                        choices=[(None, "Light"), ("carousel-dark", "Dark")],
                        help_text="Choose whether the controls, indicators, and captions are white or dark. Light controls work best when the images in the gallery are darker and dark controls appear better over light colors.",
                        max_length=13,
                        verbose_name="gallery controls",
                    ),
                ),
                (
                    "images",
                    models.ManyToManyField(
                        blank=True, related_name="content", to="website.image"
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content",
                        to="website.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Block",
                "verbose_name_plural": "Content Blocks",
                "order_with_respect_to": "page",
            },
        ),
    ]
