# Generated by Django 3.2.16 on 2022-10-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Trooper', max_length=20, verbose_name='display name')),
                ('domain', models.URLField(help_text='The domain name associated with this website', verbose_name='domain name')),
                ('description', models.CharField(blank=True, help_text='A brief description of this Troop', max_length=255, verbose_name='description')),
                ('logo', models.ImageField(blank=True, help_text='A recognizable icon to visually identify your Troop', upload_to='img', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configuration',
            },
        ),
    ]
