# Generated by Django 3.2.16 on 2022-11-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_builtin',
            field=models.CharField(blank=True, choices=[(None, 'custom webpage'), ('HOME', 'Home Page'), ('ABOUT', 'About Us'), ('CONTACT', 'Contact Form'), ('SIGNUP', 'Sign Up Form')], help_text='Some pages, such as the home page, require special treatment. If this is to be one of those special pages, you can specify it here.', max_length=7, null=True, unique=True, verbose_name='page'),
        ),
    ]
