# Generated by Django 3.2.16 on 2022-11-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_page_is_builtin'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='gallery_controls',
            field=models.CharField(blank=True, choices=[(None, 'Light'), ('carousel-dark', 'Dark')], help_text='Choose whether the controls, indicators, and captions are white or dark. Light controls work best when the images in the gallery are darker and dark controls appear better over light colors.', max_length=13, verbose_name='gallery controls'),
        ),
    ]
