# Generated by Django 3.2.16 on 2022-11-29 22:48

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_content_gallery_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='body_bg',
            field=colorfield.fields.ColorField(default='#d6cebd', image_field=None, max_length=18, samples=[('#ce1126', 'Scouting Red'), ('#003f87', 'Scouting Blue'), ('#d6cebd', 'Scouting Tan'), ('#515354', 'Warm Gray'), ('#243e2c', 'Olive'), ('#fdc116', 'Gold'), ('#ffffff', 'White'), ('#c54250', 'Light Red'), ('#860d1a', 'Dark Red'), ('#9ab3d5', 'Pale Blue'), ('#003366', 'Dark Blue'), ('#e9e9e4', 'Light Tan'), ('#ad9d7b', 'Dark Tan'), ('#858787', 'Pale Gray'), ('#232528', 'Dark Gray')], verbose_name='Body Background Color'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='navbar_bg',
            field=colorfield.fields.ColorField(default='#243e2c', image_field=None, max_length=18, samples=[('#ce1126', 'Scouting Red'), ('#003f87', 'Scouting Blue'), ('#d6cebd', 'Scouting Tan'), ('#515354', 'Warm Gray'), ('#243e2c', 'Olive'), ('#fdc116', 'Gold'), ('#ffffff', 'White'), ('#c54250', 'Light Red'), ('#860d1a', 'Dark Red'), ('#9ab3d5', 'Pale Blue'), ('#003366', 'Dark Blue'), ('#e9e9e4', 'Light Tan'), ('#ad9d7b', 'Dark Tan'), ('#858787', 'Pale Gray'), ('#232528', 'Dark Gray')], verbose_name='Navbar Background Color'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='primary',
            field=colorfield.fields.ColorField(default='#003f87', image_field=None, max_length=18, samples=[('#ce1126', 'Scouting Red'), ('#003f87', 'Scouting Blue'), ('#d6cebd', 'Scouting Tan'), ('#515354', 'Warm Gray'), ('#243e2c', 'Olive'), ('#fdc116', 'Gold'), ('#ffffff', 'White'), ('#c54250', 'Light Red'), ('#860d1a', 'Dark Red'), ('#9ab3d5', 'Pale Blue'), ('#003366', 'Dark Blue'), ('#e9e9e4', 'Light Tan'), ('#ad9d7b', 'Dark Tan'), ('#858787', 'Pale Gray'), ('#232528', 'Dark Gray')], verbose_name='Primary Color'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='secondary',
            field=colorfield.fields.ColorField(default='#515354', image_field=None, max_length=18, samples=[('#ce1126', 'Scouting Red'), ('#003f87', 'Scouting Blue'), ('#d6cebd', 'Scouting Tan'), ('#515354', 'Warm Gray'), ('#243e2c', 'Olive'), ('#fdc116', 'Gold'), ('#ffffff', 'White'), ('#c54250', 'Light Red'), ('#860d1a', 'Dark Red'), ('#9ab3d5', 'Pale Blue'), ('#003366', 'Dark Blue'), ('#e9e9e4', 'Light Tan'), ('#ad9d7b', 'Dark Tan'), ('#858787', 'Pale Gray'), ('#232528', 'Dark Gray')], verbose_name='Secondary Color'),
        ),
    ]
