# Generated by Django 3.2.16 on 2022-12-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20221129_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='footer_text',
            field=models.TextField(blank=True, verbose_name='footer'),
        ),
    ]
