# Generated by Django 3.2.16 on 2023-01-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_configuration_footer_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('navbar_order',), 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AddField(
            model_name='page',
            name='navbar_order',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Specify the order this page should appear on the site's navigation bar.", null=True, unique=True, verbose_name='navigation order'),
        ),
    ]
