# Generated by Django 4.2 on 2023-04-12 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("address_book", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Outing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("destination", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField()),
                ("departs_at", models.DateTimeField()),
                ("returns_at", models.DateTimeField()),
                (
                    "departs_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="address_book.address",
                    ),
                ),
            ],
            options={
                "verbose_name": "Outing",
                "verbose_name_plural": "Outings",
                "ordering": ["-departs_at"],
            },
        ),
        migrations.CreateModel(
            name="OutingLeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SPONSOR", "Sponsor"),
                            ("CO_SPONSOR", "Co-sponsor"),
                            ("SCOUTMASTER", "Scoutmaster"),
                            ("ASSISTANT", "Assistant Scoutmaster"),
                            ("SPL", "Senior Patrol Leader"),
                            ("ASPL", "Assistant Senior Patrol Leader"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "outing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="outings.outing"
                    ),
                ),
            ],
            options={
                "verbose_name": "Outing Leader",
                "verbose_name_plural": "Outing Leaders",
                "db_table": "outings_outing_leaders",
            },
        ),
        migrations.AddField(
            model_name="outing",
            name="leaders",
            field=models.ManyToManyField(
                through="outings.OutingLeader", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="outing",
            name="returns_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="address_book.address",
            ),
        ),
        migrations.AddConstraint(
            model_name="outingleader",
            constraint=models.UniqueConstraint(
                fields=("outing", "leader"), name="unique_outing_leader"
            ),
        ),
    ]
