# Generated by Django 3.2.16 on 2022-10-21 15:43

from django.db import migrations, models
import trooper.members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, help_text='A profile photo is used in the site directory to assist members match names with faces. A good photo is one taken from the shoulders up with the face clearly visible. Photos are only available to active members and never shared outside of the Troop.', null=True, upload_to=trooper.members.models.get_avatar_upload_to, verbose_name='profile picture'),
        ),
    ]
