# Generated by Django 3.2.16 on 2022-12-02 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date of birth'),
            preserve_default=False,
        ),
    ]
