# Generated by Django 3.2.16 on 2022-12-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='nickname',
            field=models.CharField(blank=True, help_text='The name this member prefers to be known by.', max_length=100, verbose_name='nickname'),
        ),
        migrations.AddField(
            model_name='member',
            name='suffix',
            field=models.CharField(blank=True, max_length=10, verbose_name='suffix'),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='last name'),
        ),
    ]
