# Generated by Django 3.2.16 on 2022-12-06 16:08

from django.db import migrations, models
import trooper.members.validators


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20221206_0109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['last_name', 'nickname', 'first_name'], 'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(validators=[trooper.members.validators.date_of_birth_validator], verbose_name='date of birth'),
        ),
    ]
