# Generated by Django 3.2.16 on 2023-01-11 16:20

from django.db import migrations, models
import trooper.members.validators


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, validators=[trooper.members.validators.date_of_death_validator], verbose_name='date of death'),
        ),
    ]
