# Generated by Django 3.2.16 on 2023-01-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_date_of_death'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='middle name'),
        ),
    ]
