# Generated by Django 3.2.16 on 2023-01-25 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_familymember_family'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='familymember',
            table='family_member',
        ),
    ]
