# Generated by Django 3.2.17 on 2023-02-13 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_familymember_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='avatar',
            new_name='photo',
        ),
    ]
