# Generated by Django 3.2.17 on 2023-02-14 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_rename_avatar_member_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', related_query_name='family_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
