# Generated by Django 3.2.17 on 2023-02-16 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_alter_familymember_member'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='familymember',
            table='members_family_member',
        ),
    ]
