# Generated by Django 3.2.18 on 2023-03-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_familymember_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familymember',
            options={'ordering': ('-role', 'member__date_of_birth'), 'verbose_name': 'Family Member', 'verbose_name_plural': 'Family Members'},
        ),
        migrations.AddConstraint(
            model_name='familymember',
            constraint=models.UniqueConstraint(fields=('family', 'member'), name='unique_family_member'),
        ),
    ]
