# Generated by Django 4.2 on 2023-04-12 18:46

from django.db import migrations, models
import recurrence.fields
import trooper.calendars.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "file",
                    models.FileField(
                        upload_to=trooper.calendars.models.get_attachment_upload,
                        verbose_name="file",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attachment",
                "verbose_name_plural": "Attachments",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("title", models.CharField(max_length=100, verbose_name="title")),
                ("begins_at", models.DateTimeField(verbose_name="begins")),
                (
                    "ends_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="ends"),
                ),
                ("recurrences", recurrence.fields.RecurrenceField(blank=True)),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="location"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("url", models.URLField(blank=True, verbose_name="URL")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TENTATIVE", "Tentative"),
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Canceled"),
                        ],
                        default="CONFIRMED",
                        max_length=9,
                        verbose_name="status",
                    ),
                ),
                (
                    "rsvp_required",
                    models.BooleanField(default=False, verbose_name="RSVP"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "last_modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["begins_at"],
            },
        ),
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("CHAIR", "Chair"),
                            ("REQ-PARTICIPANT", "Required"),
                            ("OPT-PARTICIPANT", "Optional"),
                            ("NON-PARTICIPANT", "Inform Only"),
                        ],
                        default="REQ-PARTICIPANT",
                        max_length=15,
                        verbose_name="participant role",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                            ("TENTATIVE", "Tentative"),
                            ("NEEDS-ACTION", "no response"),
                        ],
                        default="NEEDS-ACTION",
                        max_length=12,
                        verbose_name="response",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting Invitation",
                "verbose_name_plural": "Meeting Invitations",
            },
        ),
    ]
