# Generated by Django 4.2 on 2023-04-12 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("calendars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invite",
            name="attendee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="invite",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="calendars.event"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="attachments",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="calendars.attachment"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(
                blank=True,
                related_name="events",
                through="calendars.Invite",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="calendars.category"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events_organized",
                related_query_name="organized_event",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
